Repository eclipse-tractusx/bpdm, pull requests merged in 2024-11, with the labels that each got.

#1108 fix(Pool): retrieving legacy legal form data
  CHANGELOG.md
  bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/entity/LegalFormDb.kt
  bpdm-pool/src/main/resources/db/migration/V6_2_0_4__make_legal_form_active_not_nullable.sql
Labels: bug

#1118 chore(bpdm): Upload bpdm OpenAPI documents to Tractus-X API-Hub
  .tractusx
Labels: documentation, github_actions

#1119 docs(bpdm): update openApi spec for rc5
  docs/api/gate.json
  docs/api/gate.yaml
  docs/api/orchestrator.json
  docs/api/orchestrator.yaml
  docs/api/pool.json
  docs/api/pool.yaml
Labels: documentation

#1129 docs(Postman): update EDC consumer collection
  docs/postman/EDC BPDM Consumer.postman_collection.json
Labels: documentation

#1128 docs(Postman): update EDC provider setup collection
  docs/postman/EDC Provider Setup.postman_collection.json
Labels: documentation

#1132 docs(charts): update helm chart README for app 6.2.0
  charts/bpdm/CHANGELOG.md
  charts/bpdm/Chart.yaml
  charts/bpdm/README.md
  charts/bpdm/charts/bpdm-cleaning-service-dummy/CHANGELOG.md
  charts/bpdm/charts/bpdm-cleaning-service-dummy/Chart.yaml
  charts/bpdm/charts/bpdm-cleaning-service-dummy/README.md
  charts/bpdm/charts/bpdm-common/CHANGELOG.md
  charts/bpdm/charts/bpdm-common/Chart.yaml
  charts/bpdm/charts/bpdm-gate/CHANGELOG.md
  charts/bpdm/charts/bpdm-gate/Chart.yaml
  charts/bpdm/charts/bpdm-gate/README.md
  charts/bpdm/charts/bpdm-orchestrator/CHANGELOG.md
  charts/bpdm/charts/bpdm-orchestrator/Chart.yaml
  charts/bpdm/charts/bpdm-orchestrator/README.md
  charts/bpdm/charts/bpdm-pool/CHANGELOG.md
  charts/bpdm/charts/bpdm-pool/Chart.yaml
  charts/bpdm/charts/bpdm-pool/README.md
Labels: documentation

#1131 docs(api): update api README for 6.2.0
  docs/api/README.md
  docs/architecture/11_Risks_And_Technical_Debts.md
Labels: documentation

#1133 docs(postman): remove the outdated BPDM tests Postman collection
  docs/postman/BPDM Tests.postman_collection.json
Labels: documentation

#1135 docs(README): rework the Github workflows section
  README.md
  docs/developer/README.md
Labels: documentation

#1136 cicd(Chart Test): upgrade the default kubernetes version to 1.31
  .github/workflows/app-test-charts.yaml
Labels: github_actions

#1137 docs(Arc42): removed outdated technical debts
  docs/architecture/11_Risks_And_Technical_Debts.md
Labels: documentation

#1123 docs(INSTALL): update to version 6.2.0 documentation
  INSTALL.md
Labels: documentation

#1138 docs(bpdm):updated legal docs for cleaning and orchestrator service with snapshot version
  bpdm-cleaning-service-dummy/pom.xml
  bpdm-orchestrator/pom.xml
  charts/bpdm/Chart.yaml
  charts/bpdm/charts/bpdm-cleaning-service-dummy/Chart.yaml
  charts/bpdm/charts/bpdm-gate/Chart.yaml
  charts/bpdm/charts/bpdm-orchestrator/Chart.yaml
  charts/bpdm/charts/bpdm-pool/Chart.yaml
  pom.xml
Labels: documentation
