Repository eclipse-tractusx/bpdm, pull requests merged in 2024-07, with the labels that each got.

#988 fix(gate): Starting Golden Record Process Without Changes
  CHANGELOG.md
  bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/BusinessPartnerService.kt
Labels: bug

#989 fix(gate): Assigning Wrong Task-Ids
  CHANGELOG.md
  bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/TaskCreationService.kt
Labels: bug

#1002 ci(trivy): let trivy regularly check latest containers
  .github/workflows/trivy.yml
Labels: enhancement

#1016 Create trufflehog.yml
  .github/workflows/trufflehog.yml
Labels: github_actions
