Repository eclipse-tractusx/bpdm, pull requests merged in 2024-12, with the labels that each got.

#1142 fix(bpdm-gate): fetched and attached legal name of entity while performing partner upload process.
  CHANGELOG.md
  bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/PartnerUploadService.kt
  bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/util/PartnerFileUtil.kt
  bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/PartnerUploadControllerIT.kt
Labels: bug, enhancement

#1091 feat(Orchestrator): ignore resolutions for already resolved steps
  CHANGELOG.md
  bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/service/GoldenRecordTaskStateMachine.kt
  bpdm-orchestrator/src/test/kotlin/org/eclipse/tractusx/bpdm/orchestrator/controller/GoldenRecordTaskControllerIT.kt
  bpdm-orchestrator/src/test/kotlin/org/eclipse/tractusx/bpdm/orchestrator/service/GoldenRecordTaskStateMachineIT.kt
Labels: enhancement

#1146 feat: endpoint to return bpnl/s/a based on the requested identifiers
  CHANGELOG.md
  DEPENDENCIES
  bpdm-common-test/src/main/kotlin/org/eclipse/tractusx/bpdm/test/testdata/pool/BusinessPartnerVerboseValues.kt
  bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/PoolBpnApi.kt
  bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/client/BpnApiClient.kt
  bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/model/request/BpnRequestIdentifierSearchRequest.kt
  bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/model/response/BpnRequestIdentifierMappingDto.kt
  bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/controller/BpnController.kt
  bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/BusinessPartnerFetchService.kt
  bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/controller/BpnControllerIT.kt
  docs/api/pool.json
  docs/api/pool.yaml
Labels: enhancement, standards-relevant

#1003 feat(bpdm-gate): Extend error code
  CHANGELOG.md
  bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/exception/GateErrorCodes.kt
  bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/response/SharingStateDto.kt
  bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/TaskResolutionServices.kt
  bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/BusinessPartnerControllerAndSharingControllerIT.kt
  bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/BusinessPartnerControllerIT.kt
  bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/TaskErrorDto.kt
  bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/TaskErrorType.kt
  bpdm-orchestrator/src/main/resources/db/migration/V6_3_0_0__add_extend_error_code.sql
  docs/api/gate.yaml
  docs/api/orchestrator.yaml
Labels: enhancement, standards-relevant

#1147 build(pom): explicitly specify kotlin api and language version
  pom.xml
Labels: bug

#1145 feat(Central-IDP): increase Central-IDP version to 4.0.0
  .github/workflows/app-test-charts.yaml
  bpdm-common-test/src/main/resources/keycloak/CX-Central.json
  charts/bpdm/CHANGELOG.md
  charts/bpdm/Chart.yaml
  charts/bpdm/charts/bpdm-cleaning-service-dummy/CHANGELOG.md
  charts/bpdm/charts/bpdm-cleaning-service-dummy/Chart.yaml
  charts/bpdm/charts/bpdm-gate/CHANGELOG.md
  charts/bpdm/charts/bpdm-gate/Chart.yaml
  charts/bpdm/charts/bpdm-orchestrator/CHANGELOG.md
  charts/bpdm/charts/bpdm-orchestrator/Chart.yaml
  charts/bpdm/charts/bpdm-pool/CHANGELOG.md
  charts/bpdm/charts/bpdm-pool/Chart.yaml
  charts/bpdm/values.yaml
Labels: enhancement

#1070 feat(bpdm-system-test): golden record tester module.
  CHANGELOG.md
  DEPENDENCIES
  bpdm-system-tester/README.md
  bpdm-system-tester/pom.xml
  bpdm-system-tester/src/main/kotlin/org/eclipse/tractusx/bpdm/test/system/Application.kt
  bpdm-system-tester/src/main/kotlin/org/eclipse/tractusx/bpdm/test/system/config/GateClientConfig.kt
  bpdm-system-tester/src/main/kotlin/org/eclipse/tractusx/bpdm/test/system/config/PoolClientConfig.kt
  bpdm-system-tester/src/main/kotlin/org/eclipse/tractusx/bpdm/test/system/config/TestDataConfiguration.kt
  bpdm-system-tester/src/main/kotlin/org/eclipse/tractusx/bpdm/test/system/config/TestRunData.kt
  bpdm-system-tester/src/main/kotlin/org/eclipse/tractusx/bpdm/test/system/stepdefinations/ShareGenericNoBpnStepDefs.kt
  bpdm-system-tester/src/main/kotlin/org/eclipse/tractusx/bpdm/test/system/stepdefinations/SpringTestRunConfiguration.kt
  bpdm-system-tester/src/main/kotlin/org/eclipse/tractusx/bpdm/test/system/utils/GateInputFactory.kt
  bpdm-system-tester/src/main/kotlin/org/eclipse/tractusx/bpdm/test/system/utils/GateOutputFactory.kt
  bpdm-system-tester/src/main/kotlin/org/eclipse/tractusx/bpdm/test/system/utils/StepUtils.kt
  bpdm-system-tester/src/main/resources/application.yml
  bpdm-system-tester/src/main/resources/cucumber.properties
  bpdm-system-tester/src/main/resources/cucumber/share_generic_business_partner.feature
  pom.xml
Labels: enhancement
