Repository eclipse-tractusx/bpdm, pull requests merged in 2025-01, with the labels that each got.

#1173 fix(Pool): duplicate BPN request identifier mapping entries
  CHANGELOG.md
  bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/TaskEntryBpnMapping.kt
  bpdm-pool/src/main/resources/db/migration/V6_3_0_0__fix_request_identifier_uc.sql
  bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/controller/BpnControllerIT.kt
  bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/controller/ChangelogControllerIT.kt
Labels: bug

#1174 fix(Pool): returning incomplete task results
  CHANGELOG.md
  bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/TaskResolutionMapper.kt
  bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/TaskStepBuildService.kt
  bpdm-system-tester/src/main/resources/cucumber/share_generic_business_partner.feature
Labels: bug

#1179 fix(charts): add security profiles to BPDM deployment containers
  charts/bpdm/CHANGELOG.md
  charts/bpdm/Chart.yaml
  charts/bpdm/charts/bpdm-cleaning-service-dummy/CHANGELOG.md
  charts/bpdm/charts/bpdm-common/CHANGELOG.md
  charts/bpdm/charts/bpdm-common/Chart.yaml
  charts/bpdm/charts/bpdm-common/templates/_deployment.tpl
  charts/bpdm/charts/bpdm-gate/CHANGELOG.md
  charts/bpdm/charts/bpdm-gate/values.yaml
  charts/bpdm/charts/bpdm-orchestrator/CHANGELOG.md
  charts/bpdm/charts/bpdm-pool/CHANGELOG.md
  charts/bpdm/charts/bpdm-pool/values.yaml
Labels: enhancement

#1181 refactor: implement CodeQL suggestions
  bpdm-common-test/src/main/kotlin/org/eclipse/tractusx/bpdm/test/testdata/pool/BusinessPartnerNonVerboseValues.kt
  bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/BusinessPartnerSearchService.kt
  bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/util/CreateSQLScriptToInsertRegions.kt
Labels: enhancement

#986 feat(bpdm-gate): Adding a externalSequenceTimestamp attribute to the business partner input request
  CHANGELOG.md
  bpdm-common-test/src/main/kotlin/org/eclipse/tractusx/bpdm/test/testdata/gate/BusinessPartnerNonVerboseValues.kt
  bpdm-common-test/src/main/kotlin/org/eclipse/tractusx/bpdm/test/testdata/gate/BusinessPartnerVerboseValues.kt
  bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/IBaseBusinessPartnerGateDto.kt
  bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/request/BusinessPartnerInputRequest.kt
  bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/response/BusinessPartnerDto.kt
  bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/response/BusinessPartnerOutputDto.kt
  bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/generic/BusinessPartnerDb.kt
  bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/BusinessPartnerMappings.kt
  bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/BusinessPartnerService.kt
  bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/util/BusinessPartnerCopyUtil.kt
  bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/util/Extensions.kt
  bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/util/PartnerFileUtil.kt
  bpdm-gate/src/main/resources/db/migration/V6_3_0_1__add_externalSequenceTimestamp_column.sql
  bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/auth/AuthTestBase.kt
  bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/BusinessPartnerControllerIT.kt
  docs/api/gate.yaml
Labels: enhancement, standards-relevant

#1192 fix(bpdm-gate): update outdated task result to latest stage
  CHANGELOG.md
  bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/GoldenRecordUpdateServices.kt
  bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/TaskResolutionServices.kt
  bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/BusinessPartnerControllerAndSharingControllerIT.kt
  bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/BusinessPartnerControllerIT.kt
Labels: bug

#1199 fix(bpdm-pool): added missing legal entity (BPNL) associated to address in response while performing entity search
  CHANGELOG.md
  bpdm-common-test/src/main/kotlin/org/eclipse/tractusx/bpdm/test/testdata/pool/ExpectedBusinessPartnerResultFactory.kt
  bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/ResponseMappings.kt
  bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/controller/SiteControllerIT.kt
  bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/service/TaskResolutionServiceTest.kt
Labels: bug
