Repository eclipse-tractusx/bpdm, pull requests merged in 2025-03, with the labels that each got.

#1257 build(release-25.03): BPDM 6.3.0 & BPDM Charts 5.3.0
  CHANGELOG.md
  charts/bpdm/CHANGELOG.md
  charts/bpdm/Chart.yaml
  charts/bpdm/README.md
  charts/bpdm/charts/bpdm-cleaning-service-dummy/CHANGELOG.md
  charts/bpdm/charts/bpdm-cleaning-service-dummy/Chart.yaml
  charts/bpdm/charts/bpdm-cleaning-service-dummy/README.md
  charts/bpdm/charts/bpdm-common/CHANGELOG.md
  charts/bpdm/charts/bpdm-common/Chart.yaml
  charts/bpdm/charts/bpdm-gate/CHANGELOG.md
  charts/bpdm/charts/bpdm-gate/Chart.yaml
  charts/bpdm/charts/bpdm-gate/README.md
  charts/bpdm/charts/bpdm-orchestrator/CHANGELOG.md
  charts/bpdm/charts/bpdm-orchestrator/Chart.yaml
  charts/bpdm/charts/bpdm-orchestrator/README.md
  charts/bpdm/charts/bpdm-pool/CHANGELOG.md
  charts/bpdm/charts/bpdm-pool/Chart.yaml
  charts/bpdm/charts/bpdm-pool/README.md
  docs/api/gate.json
  docs/api/gate.yaml
  docs/api/orchestrator.json
  docs/api/orchestrator.yaml
  docs/api/pool.json
  docs/api/pool.yaml
  pom.xml
Labels: enhancement

#1260 build: BPDM 6.4.0-SNAPSHOT & BPDM Charts 5.4.0-SNAPSHOT
  CHANGELOG.md
  charts/bpdm/CHANGELOG.md
  charts/bpdm/Chart.yaml
  charts/bpdm/README.md
  charts/bpdm/charts/bpdm-cleaning-service-dummy/CHANGELOG.md
  charts/bpdm/charts/bpdm-cleaning-service-dummy/Chart.yaml
  charts/bpdm/charts/bpdm-cleaning-service-dummy/README.md
  charts/bpdm/charts/bpdm-common/CHANGELOG.md
  charts/bpdm/charts/bpdm-common/Chart.yaml
  charts/bpdm/charts/bpdm-gate/CHANGELOG.md
  charts/bpdm/charts/bpdm-gate/Chart.yaml
  charts/bpdm/charts/bpdm-gate/README.md
  charts/bpdm/charts/bpdm-orchestrator/CHANGELOG.md
  charts/bpdm/charts/bpdm-orchestrator/Chart.yaml
  charts/bpdm/charts/bpdm-orchestrator/README.md
  charts/bpdm/charts/bpdm-pool/CHANGELOG.md
  charts/bpdm/charts/bpdm-pool/Chart.yaml
  charts/bpdm/charts/bpdm-pool/README.md
  docs/api/gate.json
  docs/api/gate.yaml
  docs/api/orchestrator.json
  docs/api/orchestrator.yaml
  docs/api/pool.json
  docs/api/pool.yaml
  pom.xml
Labels: enhancement

#1267 cicd(Workflows): remove OS vulnerabilities from trivy pull request check
  .github/workflows/app-test-trivy.yaml
Labels: github_actions

#1266 cicd: remove the license-check plugin from any maven phase
  pom.xml
Labels: enhancement

#1265 feat(Gate)!: remove DELETE endpoint of relation controller
  CHANGELOG.md
  bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/GateRelationApi.kt
  bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/client/RelationApiClient.kt
  bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/controller/RelationController.kt
  bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/IRelationService.kt
  bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/RelationService.kt
  bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/auth/AuthAdminIT.kt
  bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/auth/AuthInputConsumerIT.kt
  bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/auth/AuthInputManagerIT.kt
  bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/auth/AuthOutputConsumerIT.kt
  bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/auth/AuthTestBase.kt
  bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/auth/NoAuthIT.kt
  bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/RelationIsManagedByIT.kt
  docs/api/gate.json
  docs/api/gate.yaml
Labels: enhancement, Breaking

#1268 Feat/relation api delete post
  CHANGELOG.md
  bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/GateRelationApi.kt
  bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/client/RelationApiClient.kt
  bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/request/RelationPostRequest.kt
  bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/controller/RelationController.kt
  bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/IRelationService.kt
  bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/RelationService.kt
  bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/auth/AuthAdminIT.kt
  bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/auth/AuthInputConsumerIT.kt
  bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/auth/AuthInputManagerIT.kt
  bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/auth/AuthOutputConsumerIT.kt
  bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/auth/AuthTestBase.kt
  bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/auth/NoAuthIT.kt
  bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/RelationIsManagedByIT.kt
  docs/api/gate.json
  docs/api/gate.yaml
Labels: enhancement, Breaking

#1276 build(dep): overwrite spring-security-crypto dependency version
  DEPENDENCIES
  pom.xml
Labels: enhancement

#1269 Feat/relation api post search
  CHANGELOG.md
  bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/GateRelationApi.kt
  bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/client/RelationApiClient.kt
  bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/request/RelationSearchRequest.kt
  bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/controller/RelationController.kt
  bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/auth/AuthAdminIT.kt
  bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/auth/AuthInputConsumerIT.kt
  bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/auth/AuthInputManagerIT.kt
  bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/auth/AuthOutputConsumerIT.kt
  bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/auth/AuthTestBase.kt
  bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/auth/NoAuthIT.kt
  bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/RelationIsManagedByIT.kt
  docs/api/gate.json
  docs/api/gate.yaml
Labels: enhancement, Breaking

#1289 feat(Gate): remove the relation constraint checks
  CHANGELOG.md
  bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/exception/BpdmInvalidRelationException.kt
  bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/exception/GateExceptionHandler.kt
  bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/BusinessPartnerService.kt
  bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/IRelationConstraintProvider.kt
  bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/IRelationService.kt
  bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/RelationConstraintProvider.kt
  bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/RelationService.kt
  bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/RelationControllerIT.kt
  bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/RelationIsManagedByIT.kt
Labels: enhancement, Breaking

#1291 feat(bpdm-pool): added functionality to consume relation golden record tasks
  CHANGELOG.md
  bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/BusinessPartnerRelations.kt
  bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/repository/RelationRepository.kt
  bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/TaskRelationsBatchResolutionService.kt
  bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/TaskRelationsStepBuildService.kt
  bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/service/TaskRelationsResolutionServiceTest.kt
Labels: enhancement

#1292 Feat/gate/create relation tasks
  CHANGELOG.md
  bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/RelationSharingStateDto.kt
  bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/config/GoldenRecordProcessConfigProperties.kt
  bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/config/GoldenRecordTaskConfiguration.kt
  bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/RelationSharingStateDb.kt
  bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/repository/RelationRepository.kt
  bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/repository/RelationStageRepository.kt
  bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/repository/SharingStateRepository.kt
  bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/RelationSharingStateService.kt
  bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/RelationTaskCreationService.kt
  bpdm-gate/src/main/resources/application.yml
  bpdm-gate/src/main/resources/db/migration/V7_0_0_2__add_relation_golden_record_process_properties.sql
  bpdm-gate/src/main/resources/db/migration/V7_0_0_3__add_is_staged_relation_property.sql
  bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/SharingStateControllerIT.kt
  bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/service/RelationTaskCreationServiceIT.kt
  bpdm-gate/src/test/resources/application-test.yml
Labels: enhancement
