Repository eclipse-tractusx/bpdm, pull requests merged in 2025-04, with the labels that each got.

#1296 cicd(Workflows): change trivy exit code
  .github/workflows/trivy.yml
Labels: github_actions

#1302 feat(bpdm-orchestrator): api version increased with simultaneous v6 support
  CHANGELOG.md
  bpdm-cleaning-service-dummy/src/test/kotlin/org/eclipse/tractusx/bpdm/cleaning/service/CleaningServiceApiCallsTest.kt
  bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/config/OpenApiConfig.kt
  bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/service/GoldenRecordUpdateServiceIT.kt
  bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/service/RelationTaskCreationServiceIT.kt
  bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/service/RelationTaskResolutionServiceIT.kt
  bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/util/MockAndAssertUtils.kt
  bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/ApiCommons.kt
  bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/FinishedTaskEventApi.kt
  bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/GoldenRecordTaskApi.kt
  bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/RelationsFinishedTaskEventApi.kt
  bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/RelationsGoldenRecordTaskApi.kt
  bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/client/FinishedTaskEventApiClient.kt
  bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/client/GoldenRecordTaskApiClient.kt
  bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/client/RelationsFinishedTaskEventApiClient.kt
  bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/client/RelationsGoldenRecordTaskApiClient.kt
  docs/api/orchestrator.json
  docs/api/orchestrator.yaml
Labels: enhancement

#1310 Feat/pool/relation strategies
  bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/dto/UpsertResult.kt
  bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/dto/UpsertType.kt
  bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/repository/RelationRepository.kt
  bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/AlternativeHeadquarterRelationUpsertService.kt
  bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/IRelationUpsertStrategyService.kt
  bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/RelationUpsertService.kt
  bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/TaskRelationsStepBuildService.kt
  bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/service/TaskRelationsResolutionServiceTest.kt
  bpdm-system-tester/src/main/kotlin/org/eclipse/tractusx/bpdm/test/system/stepdefinations/BusinessPartnerRelationStepDefs.kt
  bpdm-system-tester/src/main/kotlin/org/eclipse/tractusx/bpdm/test/system/utils/StepUtils.kt
  bpdm-system-tester/src/main/kotlin/org/eclipse/tractusx/bpdm/test/system/utils/TestRepository.kt
  bpdm-system-tester/src/main/resources/cucumber/share_business_partner_relation.feature
Labels: enhancement

#1317 test(System): fix race condition when reserving tasks
  bpdm-system-tester/src/main/kotlin/org/eclipse/tractusx/bpdm/test/system/stepdefinations/BusinessPartnerRelationStepDefs.kt
  bpdm-system-tester/src/main/kotlin/org/eclipse/tractusx/bpdm/test/system/utils/TestRepository.kt
Labels: enhancement

#1313 feat(Pool): add additional identifier types
  bpdm-pool/src/main/resources/db/migration/V7_0_0_2__create_identifier_types.sql
Labels: enhancement

#1318 docs: renaming attributes and edc assets as per the standards 25.06
  docs/postman/EDC Provider Setup.postman_collection.json
Labels: enhancement

#1330 feat(Gate): business partner and relation endpoint paths
  CHANGELOG.md
  bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/ApiCommons.kt
  bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/GateChangelogApi.kt
  bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/client/ChangelogApiClient.kt
  docs/api/gate.json
  docs/api/gate.yaml
Labels: enhancement, Breaking
