Repository eclipse-tractusx/bpdm, pull requests merged in 2025-02, with the labels that each got.

#1180 Fix/charts/initcontainer memory cpu
  charts/bpdm/CHANGELOG.md
  charts/bpdm/charts/bpdm-cleaning-service-dummy/CHANGELOG.md
  charts/bpdm/charts/bpdm-common/CHANGELOG.md
  charts/bpdm/charts/bpdm-common/templates/_deployment.tpl
  charts/bpdm/charts/bpdm-gate/CHANGELOG.md
  charts/bpdm/charts/bpdm-orchestrator/CHANGELOG.md
  charts/bpdm/charts/bpdm-pool/CHANGELOG.md
Labels: enhancement

#1204 cicd(chart-test): increase the default kubernetes version to v1.32.1
  .github/workflows/app-test-charts.yaml
Labels: github_actions

#1205 docs(DEPENDENCIES): update with approved cucumber dependencies
  DEPENDENCIES
Labels: documentation

#1206 cicd(Docker): build docker containers for multi-platform
  .github/workflows/deploy-docker.yaml
Labels: github_actions

#1210 fix(Pool): returning the most-up-to-date legal and site main address
  CHANGELOG.md
  bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/TaskResolutionMapper.kt
  bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/TaskStepBuildService.kt
Labels: bug

#1211 cicd(Workflows): fix deployment of multi-platform docker images
  .github/workflows/deploy-docker.yaml
Labels: github_actions

#1212 docs(admin): add small admin guide
  docs/README.md
  docs/admin/README.md
Labels: documentation

#1221 build(deps): overwrite json-smart dependency version
  DEPENDENCIES
  pom.xml
Labels: bug

#1226 build(deps): overwrite netty-handler version to fix vulnerability
  DEPENDENCIES
  pom.xml
Labels: bug, dependencies

#1241 docs: update EDC provider and consumer Postman collections
  docs/postman/EDC BPDM Consumer.postman_collection.json
  docs/postman/EDC Provider Setup.postman_collection.json
Labels: documentation

#1247 fix(bpdm-gate): added missing value for externalSequenceTimestamp attribute in response
  bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/BusinessPartnerMappings.kt
Labels: bug
